### ISSUE TITLE
Lazily compare classes when using harness.classes

### ISSUE THREAD

**Issue by kitsonk** [dojo/test-extras#26]
**Enhancement**

We should only compare `true` classes when the harness `.classes()` is used. Currently the order of the calls has to be preserved which is awkward and difficult. This shouldn't be done though when this function is not used, to test when the class state is being maintained outside of the widget-core helper functions.

**Comment by agubler** [comment]
This is be addressed by #21

**Comment by kitsonk** [comment]
Now we have a related issue. 😄

When are we going to release the other changes in `widget-core` so we can get #21 merged?

**Comment by agubler** [comment]
There is a typing bug that I would like addressed when using `w` before we release `widget-core` https://github.com/dojo/widget-core/issues/464.

If I get time, i'll pick it up this week; So probably looking at early next week for a release.

**Comment by kitsonk** [comment]
Because of changes in widget-core, this has been replaced by #78
