### ISSUE TITLE
Filter out ignored properties when throwing the assertion error?

### ISSUE THREAD

**Issue by lzhoucs** [dojo/test-extras#42]
**Enhancement**

Shall we consider filtering out those ignored properties when throwing the assertion error? Since we ignore them during `diff`, if we don't ignore them when printing the error out, the console error diff log can be misleading since the error showing on the console is not the actual cause of the error. One good example is `bind`, which [becomes an ignored property](https://github.com/dojo/test-extras/pull/39), and it is a large one too. Currently the error log contains `bind`:
```
AssertionError: Render unexpected

  {
...
A   "bind": {
A     "_allClasses": {
A       "radio-m__checked__1JpbM": false,
A       "radio-m__disabled__2DHjm": false,
A       "radio-m__inputWrapper__EvHGM": false,
A       "radio-m__input__a6UKx": false,
A       "radio-m__invalid__vH9mx": false,
A       "radio-m__readonly__3WqpF": false,
A       "radio-m__required__1ZLJk": false,
A       "radio-m__root__2bqGM": false
A     },
A     "_baseThemeClassesReverseLookup": {
A       "dojo-radio": " _key",
A       "radio-m__checked__1JpbM": "checked",
A       "radio-m__disabled__2DHjm": "disabled",
A       "radio-m__inputWrapper__EvHGM": "inputWrapper",
A       "radio-m__input__a6UKx": "input",
A       "radio-m__invalid__vH9mx": "invalid",
A       "radio-m__readonly__3WqpF": "readonly",
A       "radio-m__required__1ZLJk": "required",
A       "radio-m__root__2bqGM": "root",
A       "radio-m__valid__2hLww": "valid"
A     },
A     "_bindFunctionPropertyMap": {},
A     "_cachedChildrenMap": {},
A     "_children": [
A       length: 0
A     ],
...
```

Package Version: `2.0.0-alpha.3`

**Comment by kitsonk** [comment]
A good suggestion but that will be challenging because the diff is supplied by Node.js when the two objects are supplied.

**Comment by lzhoucs** [comment]
What if we filter the ignored properties of the `actual` object right before [calling `throwAssertionError()`](https://github.com/dojo/test-extras/blob/master/src/support/assertRender.ts#L95)

**Comment by maier49** [comment]
The PR I opened up for this currently removes both ignored properties and properties whose values are ignored when they exist on both objects. When they don't exist on both objects it will still show the missing property as part of the `expected` object. 

Would it potentially make sense to instead add a placeholder value, maybe just `"PROPERTY_VALUE_IGNORED"`, on those properties in either case? That way it would be clear, whether they were missing or not, that the value doesn't matter, but that the property is still expected and was/was not present.
