### ISSUE TITLE
`.classes()` doesn't work when a new css class is added

### ISSUE THREAD

**Issue by lzhoucs** [dojo/test-extras#44]
**Bug** 

I am following the [classes section of the readme](https://github.com/dojo/test-extras#classes), but I found that it doesn't work when there's a new css class added in the `expected` vdom node in between the first and the second render. The following example demonstrates the issue(the event and aria properties are stripped off for simplicity)

**Code**
```ts
		let radio = harness(Radio);	
                radio.setProperties({
			invalid: true
		});

		const expected = v('div', {
			classes: radio.classes(css.root, css.invalid)
		}, [
			v('div', {
				classes: radio.classes(css.inputWrapper)
			}, [
				v('input', {
					classes: radio.classes(css.input)
				})
			])
		]);
		radio.expectRender(expected);  // success

		radio.setProperties({
			invalid: false
		});
		assignProperties(expected, {
			classes: radio.classes(css.root, css.valid) // new `css.valid` is added
		});
		assignChildProperties(expected, '0', {
			classes: radio.classes(css.inputWrapper)
		});
		assignChildProperties(expected, '0,0', {
			classes: radio.classes(css.input)
		});

		radio.expectRender(expected); // will fail because `css.valid: false` is included in the expected but not the actual vdom node's `classes` property.

```

Package Version: `2.0.0-alpha.3`

**Comment by agubler** [comment]
I think you have to assign from the children up rather than the parent down.

Did you try recreating the full expected nodes? Does it still fail?

**Comment by lzhoucs** [comment]
The full expected nodes are always working. When trying to utilize `assignProperties` to reuse the previous expected node, I ran into the issue. Thanks @agubler for the quick response. I'll try to assign from bottom up.

**Comment by lzhoucs** [comment]
Thanks, it worked! I'll update the readme.
