### ISSUE TITLE
Have an equivalent to callListener for calling a method that is passed as a property

### ISSUE THREAD

**Issue by kitsonk** [dojo/test-extras#48]
**Enhancement**

Listeners shouldn't return values (or their values don't matter).  That is not always the case for properties that are methods.  We should have an API that allows the value of the property to be called, since sometimes these can be injected by other widgets to allow some functionality delegation and sometimes this is required to full test the functionality of the unit.

If we had `.callProperty()` where the value returned from the method is returned to the caller and it respected the `.bind` rules of the `widget-core` this would meet this requirement.

**Comment by agubler** [comment]
`.trigger` on the new `harness` API (#102) can target both functions passed to `WNode`s created by `w()` and functions passed to VNodes created by `v()`. If the function has a result it is returned to the caller.
