### ISSUE TITLE
Rename repo and package

### ISSUE THREAD

**Issue by rishson** [dojo/test-extras#5]
Given the majority of functionality in this repo _may_ become non-`intern` specific, could we rename to `test-extra` or `test-extras`?

We could place test framework specific code in their own directories such as:

`import awesomeThing from 'testExtra/intern'` etc..

**Comment by kitsonk** [comment]
Which do you prefer. `test-extra` or `test-extras`?

**Comment by rishson** [comment]
No opinion really. If `extras` is weird, then `helpers` is fine I guess. Its more the non-interny-ness that I think is important to convey.
