### ISSUE TITLE
When adding a `key` to a `VNode` afterCreate and afterUpdate appear in the expectRender diff

### ISSUE THREAD

**Issue by tomdye** [dojo/test-extras#50]
**Bug** 

When a widget adds a `key` to one of it's `VNode`s this adds `afterCreate` and `afterUpdate` functions to the `widget.expectRender` call. 
To get around this we currently have to add `widget.listener` entries for both functions to the expected render result.

These should likely be ignored.

**Comment by agubler** [comment]
`dojo/widget-core` does not allow `afterCreate` or `afterUpdate` since moving away from Maquette for the vdom. Closing.
