### ISSUE TITLE
Regression in harness due to upstream change

### ISSUE THREAD

**Issue by kitsonk** [dojo/test-extras#52]
**Bug**

When dojo/widget-core#591 is published, it will cause a breaking change in `harness` due to its reliance on [events emitted from `WidgetBase`](https://github.com/dojo/test-extras/blob/bc724feccddfbf4272f5a9ec44bf42592d4b403e/src/harness.ts#L283-L284).

**Comment by agubler** [comment]
This is actually not a breaking change for `test-extras`, the listeners on the events `properties:changed` and `widget:children` don't seem to be required.

Have raised #53 removing them and also changes required now `invalidate` is protected.

**Comment by kitsonk** [comment]
Ah, I suspect it is because the invalidation cycle is more tightly controlled based on the flow with harness.
