### ISSUE TITLE
Add helper for running code inside of a web worker

### ISSUE THREAD

**Issue by rorticus** [dojo/test-extras#59]
When writing the tests for https://github.com/dojo/shim/issues/107 and https://github.com/dojo/core/issues/320 there was a common pattern that looked something like this:

```typescript
		'queue from webworker': function (this: any) {
			if (global.Blob === undefined || global.Worker === undefined) {
				this.skip('does not support blobs and/or web workers');
				return;
			}

			const baseUrl = location.origin;
			const dfd = this.async(10000);
			const blob = new Blob([ `(function() { 
self.addEventListener('message', function (event) {
	if(event.data.baseUrl) {
		var baseUrl = event.data.baseUrl;
		importScripts(baseUrl + '/node_modules/@dojo/loader/loader.js');

		require.config({
			baseUrl: baseUrl,
			packages: [
				{ name: '@dojo', location: 'node_modules/@dojo' }
			]
		});
		
		require(['_build/src/support/queue'], function (queue) {
			queue.queueTask(function() {
				self.postMessage('success');
			});
		});
	}
});
			})()` ], { type: 'application/javascript' });
			const worker = new Worker(URL.createObjectURL(blob));
			worker.addEventListener('error', (error) => {
				dfd.reject(new Error(error.message));
			});
			worker.addEventListener('message', ({ data: result }) => {
				if (result === 'success') {
					dfd.resolve();
				}
			});

			worker.postMessage({
				baseUrl
			});
		}
```

1. The loader is loaded with `importScripts`
2. The loader is configured to load from the source being tested
3. The loader is used to load the modules being tested
4. The code is tested and a success/failure message is emitted
5. All of that code is wrapped into a Blob and loaded into a web worker

@kitsonk mentioned it might be nice to have a helper for this kind of test!

**Comment by agubler** [comment]
I don't think that test-extras would be the right place for this "helper" now as it only now provides a harness for testing expected rendering and widget behaviours.
