### ISSUE TITLE
Update README to describe pepjs mapping requirement.

### ISSUE THREAD

**Issue by edhager** [dojo/test-extras#60]
I am working on adding unit tests to dojo.io and when I started using test-extras, I had to add this following package map to my Intern config:

> { name: 'pepjs', location: 'node_modules/pepjs/dist', main: 'pep' }

I noticed that @dojo/widgets is doing the same thing.  Without it, the loader complains about not being able to load the pepjs module.

I think the readme needs to be updated to tell people to add that package map to their loader config unless I am missing something else that would satisfy the loader.

**Comment by matt-gadd** [comment]
I think this can be closed given the changes to harness.
