### ISSUE TITLE
Better patches/shims for loadJsdom

### ISSUE THREAD

**Issue by kitsonk** [dojo/test-extras#7]
**Enhancement**

Our patches/shims/fills that we have in `loadJsdom` are a bit *hacky* in the sense they are just the minimalist things we have tried to do in order to get our tests to pass when running under jsdom.  We should probably organise these a little bit better as well as only inject them if they are actually required (to protect us from potential changes to jsdom which actually implement these).

**Comment by kitsonk** [comment]
Actually, the whole interaction with jsdom should be different.  We should create a sandboxed environment and inject our scripts into that environment.  Since JSDom 10, it behaves this way as default, but we have essentially "worked" around that to make it work like we used it before.  We should be injecting intern bootstrap into a jsdom environment and working from there, injecting anything else we need to help support the environment.

Since `widget-core` is unlikely to be able to use `test-extras` we should ensure that the changes to the approach for `loadJsdom` are reflected in its version of the loading.

**Comment by kitsonk** [comment]
We need to update the version as well, which has a new flag `pretendToBeVisual` (thanks @matt-gadd for pointing it out) which we should also enable which will support things like rAF, so less polyfills/shims.

**Comment by agubler** [comment]
test-extras no longer has a dependency (or provides) JSDom
