### ISSUE TITLE
assertRender does not compare some arrays properly

### ISSUE THREAD

**Issue by kitsonk** [dojo/test-extras#71]
**Bug**

When asserting a render, and the render returns an `[ undefined ]` as children, there is no way to compare it, providing a `[ undefined ]` still results in an assertion error being thrown.

**Code**

```ts
import assertRender from '@dojo/test-extras/support/assertRender';
import { v } from '@dojo/widget-core/d';

assertRender(v('div', {}, [ undefined ], v('div', {}, [ undefined ]);
```

**Expected behavior:**

Should not throw.

**Actual behavior:**

Throws with a `AssertionError`

**Comment by agubler** [comment]
This should not be an issue since the test-extras refactor #102
