### ISSUE TITLE
Allow a user to wait for the next invalidation before doing assertions

### ISSUE THREAD

**Issue by umaar** [dojo/test-extras#72]
**Enhancement** 

From a discussion:

> yeah, some sort of _waitForInvalidate_ might work for the harness… or `expectRender()` takes an optional flag that says that the next schedule render will occur out of turn, versus it being forced…

**Comment by agubler** [comment]
Is this still a valid issue given the test-extras refactor #102?

**Comment by agubler** [comment]
Closing this issue since the refactor in #102.
