### ISSUE TITLE
Unclear error messaging 

### ISSUE THREAD

**Issue by umaar** [dojo/test-extras#73]
**Bug** 

Package Version:

```
The currently installed groups are:

build (@dojo/cli-build-webpack) 0.1.0
create (@dojo/cli-create-app) 0.1.0
test (@dojo/cli-test-intern) 0.1.0

You are currently running @dojo/cli 0.1.0

And: "@dojo/test-extras": "~0.1.0",
```

When you call `expectRender`, it can sometimes be unclear why it fails:

```
×
Reported Test Errors:

x Suite name - test name (0.004s)
AssertionError: Render unexpected: expectRender message
```

In this example, the wording could be misinterpreted as "A render occurred, but should not have". I think it needs to be clear that the issue is the 'trees' don't match (expected vs. actual) and there should always be a diff. In this example, there is no diff. I intentionally manipulated to expected widget to recreate this error:

```js
replaceChild(expectedWidget, '0,0', 'some text here');
widget.expectRender(expectedWidget, 'message'); // this will fail, but is unclear why
```

Debugging becomes very problematic otherwise!

**Comment by agubler** [comment]
The error reporting for assertion errors using the new `expect` API should be clear as described in the latest README documentation https://github.com/dojo/test-extras#harnessexpect
