### ISSUE TITLE
compare does not work on an Array of TypedArrays

### ISSUE THREAD

**Issue by devpaul** [dojo/test-extras#75]
**Bug / Enhancement** 

Given

```
const a = [ new Int8Array(10) ];
```

this fails: https://github.com/dojo/test-extras/blob/master/src/support/compare.ts#L341-L359

because:

isArray returns false for TypedArrays,  a TypedArray's constructor is not Object, and it is not a primitive or a function. I can imagine this failing in other cases like `Object.create(null)`.

**Expected behavior:**

To compare their values

**Actual behavior:**

It threw an error "Value of array element "0" from first argument is not a primative, plain Object, or Array."

**Comment by kitsonk** [comment]
`test-extras` needs to move to `@dojo/core/compare`.  We should consider fixing this in `core` as well and finish the migration.

**Comment by agubler** [comment]
test-extras no longer uses compare since #102
